/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 5v1p2i7GvsoMJk4KqrA6F3

import { createUseStyleTokens } from "@plasmicapp/react-web";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 5v1p2i7GvsoMJk4KqrA6F3/projectModule

import projectcss from "./plasmic.module.css"; // plasmic-import: 5v1p2i7GvsoMJk4KqrA6F3/projectcss

const data = {
  base: `${projectcss.plasmic_tokens}`,
  varianted: []
};

export const _useStyleTokens = createUseStyleTokens(data, _useGlobalVariants);
