/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 77YCnrwhevb2XmBSeMeRKC
// Component: _FSqgEpedOrt

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 77YCnrwhevb2XmBSeMeRKC/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 77YCnrwhevb2XmBSeMeRKC/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 77YCnrwhevb2XmBSeMeRKC/projectcss
import sty from "./PlasmicSkillCard.module.css"; // plasmic-import: _FSqgEpedOrt/css

createPlasmicElementProxy;

export type PlasmicSkillCard__VariantMembers = {};
export type PlasmicSkillCard__VariantsArgs = {};
type VariantPropType = keyof PlasmicSkillCard__VariantsArgs;
export const PlasmicSkillCard__VariantProps = new Array<VariantPropType>();

export type PlasmicSkillCard__ArgsType = {
  text?: string;
  link?: string;
  iconSlot?: React.ReactNode;
};
type ArgPropType = keyof PlasmicSkillCard__ArgsType;
export const PlasmicSkillCard__ArgProps = new Array<ArgPropType>(
  "text",
  "link",
  "iconSlot"
);

export type PlasmicSkillCard__OverridesType = {
  outerMargin?: Flex__<"div">;
  link?: Flex__<"a"> & Partial<LinkProps>;
  freeBox?: Flex__<"div">;
  iconContainer?: Flex__<"div">;
  skill?: Flex__<"div">;
};

export interface DefaultSkillCardProps {
  text?: string;
  link?: string;
  iconSlot?: React.ReactNode;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicSkillCard__RenderFunc(props: {
  variants: PlasmicSkillCard__VariantsArgs;
  args: PlasmicSkillCard__ArgsType;
  overrides: PlasmicSkillCard__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {
          text: "skill",
          link: "/skills"
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"outerMargin"}
      data-plasmic-override={overrides.outerMargin}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.outerMargin
      )}
    >
      <PlasmicLink__
        data-plasmic-name={"link"}
        data-plasmic-override={overrides.link}
        className={classNames(
          projectcss.all,
          projectcss.a,
          projectcss.a__77YCn,
          sty.link
        )}
        component={Link}
        href={$props.link}
        legacyBehavior={false}
        platform={"nextjs"}
      >
        <div
          data-plasmic-name={"freeBox"}
          data-plasmic-override={overrides.freeBox}
          className={classNames(projectcss.all, sty.freeBox)}
        >
          <div
            data-plasmic-name={"iconContainer"}
            data-plasmic-override={overrides.iconContainer}
            className={classNames(projectcss.all, sty.iconContainer)}
          >
            {renderPlasmicSlot({
              defaultContents: null,
              value: args.iconSlot
            })}
          </div>
          <div
            data-plasmic-name={"skill"}
            data-plasmic-override={overrides.skill}
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.skill
            )}
          >
            <React.Fragment>
              {(() => {
                try {
                  return $props.text;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return "skill";
                  }
                  throw e;
                }
              })()}
            </React.Fragment>
          </div>
        </div>
      </PlasmicLink__>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  outerMargin: ["outerMargin", "link", "freeBox", "iconContainer", "skill"],
  link: ["link", "freeBox", "iconContainer", "skill"],
  freeBox: ["freeBox", "iconContainer", "skill"],
  iconContainer: ["iconContainer"],
  skill: ["skill"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  outerMargin: "div";
  link: "a";
  freeBox: "div";
  iconContainer: "div";
  skill: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSkillCard__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSkillCard__VariantsArgs;
    args?: PlasmicSkillCard__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicSkillCard__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicSkillCard__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSkillCard__ArgProps,
          internalVariantPropNames: PlasmicSkillCard__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSkillCard__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "outerMargin") {
    func.displayName = "PlasmicSkillCard";
  } else {
    func.displayName = `PlasmicSkillCard.${nodeName}`;
  }
  return func;
}

export const PlasmicSkillCard = Object.assign(
  // Top-level PlasmicSkillCard renders the root element
  makeNodeComponent("outerMargin"),
  {
    // Helper components rendering sub-elements
    link: makeNodeComponent("link"),
    freeBox: makeNodeComponent("freeBox"),
    iconContainer: makeNodeComponent("iconContainer"),
    skill: makeNodeComponent("skill"),

    // Metadata about props expected for PlasmicSkillCard
    internalVariantProps: PlasmicSkillCard__VariantProps,
    internalArgProps: PlasmicSkillCard__ArgProps
  }
);

export default PlasmicSkillCard;
/* prettier-ignore-end */
