/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 77YCnrwhevb2XmBSeMeRKC
// Component: ZAJiHSGC0jt9

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { BaseRadio } from "@plasmicpkgs/react-aria/skinny/registerRadio";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 77YCnrwhevb2XmBSeMeRKC/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 77YCnrwhevb2XmBSeMeRKC/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 77YCnrwhevb2XmBSeMeRKC/projectcss
import sty from "./PlasmicUiRadio.module.css"; // plasmic-import: ZAJiHSGC0jt9/css

createPlasmicElementProxy;

export type PlasmicUiRadio__VariantMembers = {};
export type PlasmicUiRadio__VariantsArgs = {};
type VariantPropType = keyof PlasmicUiRadio__VariantsArgs;
export const PlasmicUiRadio__VariantProps = new Array<VariantPropType>();

export type PlasmicUiRadio__ArgsType = {
  value?: string;
  label?: React.ReactNode;
  autoFocus?: boolean;
  disabled?: boolean;
  ariaLabel?: string;
};
type ArgPropType = keyof PlasmicUiRadio__ArgsType;
export const PlasmicUiRadio__ArgProps = new Array<ArgPropType>(
  "value",
  "label",
  "autoFocus",
  "disabled",
  "ariaLabel"
);

export type PlasmicUiRadio__OverridesType = {
  ariaRadio?: Flex__<typeof BaseRadio>;
};

export interface DefaultUiRadioProps {
  value?: string;
  label?: React.ReactNode;
  autoFocus?: boolean;
  disabled?: boolean;
  ariaLabel?: string;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicUiRadio__RenderFunc(props: {
  variants: PlasmicUiRadio__VariantsArgs;
  args: PlasmicUiRadio__ArgsType;
  overrides: PlasmicUiRadio__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  const [$ccVariants, setDollarCcVariants] = React.useState<
    Record<string, boolean>
  >({
    selected: false,
    hovered: false,
    pressed: false,
    focused: false,
    focusVisible: false,
    disabled: false,
    readonly: false
  });
  const updateVariant = React.useCallback(
    (changes: Record<string, boolean>) => {
      setDollarCcVariants(prev => {
        if (!Object.keys(changes).some(k => prev[k] !== changes[k])) {
          return prev;
        }
        return { ...prev, ...changes };
      });
    },
    []
  );

  return (
    <BaseRadio
      data-plasmic-name={"ariaRadio"}
      data-plasmic-override={overrides.ariaRadio}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      aria-label={args.ariaLabel}
      autoFocus={args.autoFocus}
      className={classNames(
        "__wab_instance",
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.ariaRadio
      )}
      isDisabled={args.disabled}
      plasmicUpdateVariant={updateVariant}
      value={args.value}
    >
      <div className={classNames(projectcss.all, sty.freeBox__zHHk)}>
        <div className={classNames(projectcss.all, sty.freeBox__l3C1Q)} />
      </div>
      {renderPlasmicSlot({
        defaultContents: "Option",
        value: args.label
      })}
    </BaseRadio>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  ariaRadio: ["ariaRadio"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  ariaRadio: typeof BaseRadio;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicUiRadio__OverridesType,
  DescendantsType<T>
>;

type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicUiRadio__VariantsArgs;
    args?: PlasmicUiRadio__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicUiRadio__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicUiRadio__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicUiRadio__ArgProps,
          internalVariantPropNames: PlasmicUiRadio__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicUiRadio__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "ariaRadio") {
    func.displayName = "PlasmicUiRadio";
  } else {
    func.displayName = `PlasmicUiRadio.${nodeName}`;
  }
  return func;
}

export const PlasmicUiRadio = Object.assign(
  // Top-level PlasmicUiRadio renders the root element
  makeNodeComponent("ariaRadio"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicUiRadio
    internalVariantProps: PlasmicUiRadio__VariantProps,
    internalArgProps: PlasmicUiRadio__ArgProps
  }
);

export default PlasmicUiRadio;
/* prettier-ignore-end */
