/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 77YCnrwhevb2XmBSeMeRKC
// Component: f7_eeq1__cMs

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import PageSupportCustomHeader from "../../PageSupport/PageSupportCustomHeader"; // plasmic-import: lVLsklxwqNh2/component
import PageSupportCustomFooter from "../../PageSupport/PageSupportCustomFooter"; // plasmic-import: dDACK3Z9VKbB/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 77YCnrwhevb2XmBSeMeRKC/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 77YCnrwhevb2XmBSeMeRKC/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 77YCnrwhevb2XmBSeMeRKC/projectcss
import sty from "./PlasmicPages404.module.css"; // plasmic-import: f7_eeq1__cMs/css

createPlasmicElementProxy;

export type PlasmicPages404__VariantMembers = {};
export type PlasmicPages404__VariantsArgs = {};
type VariantPropType = keyof PlasmicPages404__VariantsArgs;
export const PlasmicPages404__VariantProps = new Array<VariantPropType>();

export type PlasmicPages404__ArgsType = {};
type ArgPropType = keyof PlasmicPages404__ArgsType;
export const PlasmicPages404__ArgProps = new Array<ArgPropType>();

export type PlasmicPages404__OverridesType = {
  root?: Flex__<"div">;
  pageSupportCustomHeader?: Flex__<typeof PageSupportCustomHeader>;
  text?: Flex__<"div">;
  back?: Flex__<"a"> & Partial<LinkProps>;
  pageSupportCustomFooter?: Flex__<typeof PageSupportCustomFooter>;
};

export interface DefaultPages404Props {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicPages404__RenderFunc(props: {
  variants: PlasmicPages404__VariantsArgs;
  args: PlasmicPages404__ArgsType;
  overrides: PlasmicPages404__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
    >
      <PageSupportCustomHeader
        data-plasmic-name={"pageSupportCustomHeader"}
        data-plasmic-override={overrides.pageSupportCustomHeader}
        className={classNames("__wab_instance", sty.pageSupportCustomHeader)}
      />

      <div
        data-plasmic-name={"text"}
        data-plasmic-override={overrides.text}
        className={classNames(projectcss.all, projectcss.__wab_text, sty.text)}
      >
        {
          "404\nUh oh, looks like you ran into some wild unicyclers!\nWe couldn't find what you were looking for"
        }
      </div>
      <PlasmicLink__
        data-plasmic-name={"back"}
        data-plasmic-override={overrides.back}
        className={classNames(
          projectcss.all,
          projectcss.a,
          projectcss.a__77YCn,
          projectcss.__wab_text,
          sty.back
        )}
        component={Link}
        href={`/`}
        legacyBehavior={false}
        platform={"nextjs"}
      >
        {"\u21a9Back"}
      </PlasmicLink__>
      <PageSupportCustomFooter
        data-plasmic-name={"pageSupportCustomFooter"}
        data-plasmic-override={overrides.pageSupportCustomFooter}
        className={classNames("__wab_instance", sty.pageSupportCustomFooter)}
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "pageSupportCustomHeader",
    "text",
    "back",
    "pageSupportCustomFooter"
  ],

  pageSupportCustomHeader: ["pageSupportCustomHeader"],
  text: ["text"],
  back: ["back"],
  pageSupportCustomFooter: ["pageSupportCustomFooter"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  pageSupportCustomHeader: typeof PageSupportCustomHeader;
  text: "div";
  back: "a";
  pageSupportCustomFooter: typeof PageSupportCustomFooter;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPages404__OverridesType,
  DescendantsType<T>
>;

type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPages404__VariantsArgs;
    args?: PlasmicPages404__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicPages404__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicPages404__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicPages404__ArgProps,
          internalVariantPropNames: PlasmicPages404__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicPages404__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPages404";
  } else {
    func.displayName = `PlasmicPages404.${nodeName}`;
  }
  return func;
}

export const PlasmicPages404 = Object.assign(
  // Top-level PlasmicPages404 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    pageSupportCustomHeader: makeNodeComponent("pageSupportCustomHeader"),
    text: makeNodeComponent("text"),
    back: makeNodeComponent("back"),
    pageSupportCustomFooter: makeNodeComponent("pageSupportCustomFooter"),

    // Metadata about props expected for PlasmicPages404
    internalVariantProps: PlasmicPages404__VariantProps,
    internalArgProps: PlasmicPages404__ArgProps
  }
);

export default PlasmicPages404;
/* prettier-ignore-end */
