/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 77YCnrwhevb2XmBSeMeRKC
// Component: j2X0h4ewIXVl

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import CustomHeader from "../../CustomHeader"; // plasmic-import: lVLsklxwqNh2/component
import CustomFooter from "../../CustomFooter"; // plasmic-import: dDACK3Z9VKbB/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 77YCnrwhevb2XmBSeMeRKC/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 77YCnrwhevb2XmBSeMeRKC/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 77YCnrwhevb2XmBSeMeRKC/projectcss
import sty from "./PlasmicBlogIndexLayout.module.css"; // plasmic-import: j2X0h4ewIXVl/css

createPlasmicElementProxy;

export type PlasmicBlogIndexLayout__VariantMembers = {};
export type PlasmicBlogIndexLayout__VariantsArgs = {};
type VariantPropType = keyof PlasmicBlogIndexLayout__VariantsArgs;
export const PlasmicBlogIndexLayout__VariantProps =
  new Array<VariantPropType>();

export type PlasmicBlogIndexLayout__ArgsType = {
  postListSlot?: React.ReactNode;
};
type ArgPropType = keyof PlasmicBlogIndexLayout__ArgsType;
export const PlasmicBlogIndexLayout__ArgProps = new Array<ArgPropType>(
  "postListSlot"
);

export type PlasmicBlogIndexLayout__OverridesType = {
  root?: Flex__<"div">;
  customHeader?: Flex__<typeof CustomHeader>;
  freeBox?: Flex__<"div">;
  customFooter?: Flex__<typeof CustomFooter>;
};

export interface DefaultBlogIndexLayoutProps {
  postListSlot?: React.ReactNode;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicBlogIndexLayout__RenderFunc(props: {
  variants: PlasmicBlogIndexLayout__VariantsArgs;
  args: PlasmicBlogIndexLayout__ArgsType;
  overrides: PlasmicBlogIndexLayout__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
    >
      <CustomHeader
        data-plasmic-name={"customHeader"}
        data-plasmic-override={overrides.customHeader}
        className={classNames("__wab_instance", sty.customHeader)}
      />

      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames(projectcss.all, sty.freeBox)}
      >
        {renderPlasmicSlot({
          defaultContents: (
            <React.Fragment>
              <div className={classNames(projectcss.all, sty.freeBox__bdciq)} />

              <div
                className={classNames(projectcss.all, sty.freeBox___7A0Ek)}
              />
            </React.Fragment>
          ),
          value: args.postListSlot
        })}
      </div>
      <CustomFooter
        data-plasmic-name={"customFooter"}
        data-plasmic-override={overrides.customFooter}
        className={classNames("__wab_instance", sty.customFooter)}
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "customHeader", "freeBox", "customFooter"],
  customHeader: ["customHeader"],
  freeBox: ["freeBox"],
  customFooter: ["customFooter"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  customHeader: typeof CustomHeader;
  freeBox: "div";
  customFooter: typeof CustomFooter;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicBlogIndexLayout__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicBlogIndexLayout__VariantsArgs;
    args?: PlasmicBlogIndexLayout__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicBlogIndexLayout__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicBlogIndexLayout__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicBlogIndexLayout__ArgProps,
          internalVariantPropNames: PlasmicBlogIndexLayout__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicBlogIndexLayout__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicBlogIndexLayout";
  } else {
    func.displayName = `PlasmicBlogIndexLayout.${nodeName}`;
  }
  return func;
}

export const PlasmicBlogIndexLayout = Object.assign(
  // Top-level PlasmicBlogIndexLayout renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    customHeader: makeNodeComponent("customHeader"),
    freeBox: makeNodeComponent("freeBox"),
    customFooter: makeNodeComponent("customFooter"),

    // Metadata about props expected for PlasmicBlogIndexLayout
    internalVariantProps: PlasmicBlogIndexLayout__VariantProps,
    internalArgProps: PlasmicBlogIndexLayout__ArgProps
  }
);

export default PlasmicBlogIndexLayout;
/* prettier-ignore-end */
