/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 77YCnrwhevb2XmBSeMeRKC
// Component: j2X0h4ewIXVl

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import PageSupportCustomHeader from "../../PageSupport/PageSupportCustomHeader"; // plasmic-import: lVLsklxwqNh2/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 77YCnrwhevb2XmBSeMeRKC/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 77YCnrwhevb2XmBSeMeRKC/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicPagesBlogIndexLayout.module.css"; // plasmic-import: j2X0h4ewIXVl/css

createPlasmicElementProxy;

export type PlasmicPagesBlogIndexLayout__VariantMembers = {};
export type PlasmicPagesBlogIndexLayout__VariantsArgs = {};
type VariantPropType = keyof PlasmicPagesBlogIndexLayout__VariantsArgs;
export const PlasmicPagesBlogIndexLayout__VariantProps =
  new Array<VariantPropType>();

export type PlasmicPagesBlogIndexLayout__ArgsType = {
  postListSlot?: React.ReactNode;
};
type ArgPropType = keyof PlasmicPagesBlogIndexLayout__ArgsType;
export const PlasmicPagesBlogIndexLayout__ArgProps = new Array<ArgPropType>(
  "postListSlot"
);

export type PlasmicPagesBlogIndexLayout__OverridesType = {
  root?: Flex__<"div">;
  pageSupportCustomHeader?: Flex__<typeof PageSupportCustomHeader>;
  freeBox?: Flex__<"div">;
};

export interface DefaultPagesBlogIndexLayoutProps {
  postListSlot?: React.ReactNode;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicPagesBlogIndexLayout__RenderFunc(props: {
  variants: PlasmicPagesBlogIndexLayout__VariantsArgs;
  args: PlasmicPagesBlogIndexLayout__ArgsType;
  overrides: PlasmicPagesBlogIndexLayout__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "all",
        "root_reset_77YCnrwhevb2XmBSeMeRKC",
        "plasmic_default_styles",
        "plasmic_mixins",
        styleTokensClassNames,
        sty.root
      )}
    >
      <PageSupportCustomHeader
        data-plasmic-name={"pageSupportCustomHeader"}
        data-plasmic-override={overrides.pageSupportCustomHeader}
        className={classNames("__wab_instance", sty.pageSupportCustomHeader)}
      />

      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames("all", sty.freeBox)}
      >
        {renderPlasmicSlot({
          defaultContents: null,
          value: args.postListSlot
        })}
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "pageSupportCustomHeader", "freeBox"],
  pageSupportCustomHeader: ["pageSupportCustomHeader"],
  freeBox: ["freeBox"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  pageSupportCustomHeader: typeof PageSupportCustomHeader;
  freeBox: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPagesBlogIndexLayout__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPagesBlogIndexLayout__VariantsArgs;
    args?: PlasmicPagesBlogIndexLayout__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicPagesBlogIndexLayout__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicPagesBlogIndexLayout__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicPagesBlogIndexLayout__ArgProps,
          internalVariantPropNames: PlasmicPagesBlogIndexLayout__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicPagesBlogIndexLayout__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPagesBlogIndexLayout";
  } else {
    func.displayName = `PlasmicPagesBlogIndexLayout.${nodeName}`;
  }
  return func;
}

export const PlasmicPagesBlogIndexLayout = Object.assign(
  // Top-level PlasmicPagesBlogIndexLayout renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    pageSupportCustomHeader: makeNodeComponent("pageSupportCustomHeader"),
    freeBox: makeNodeComponent("freeBox"),

    // Metadata about props expected for PlasmicPagesBlogIndexLayout
    internalVariantProps: PlasmicPagesBlogIndexLayout__VariantProps,
    internalArgProps: PlasmicPagesBlogIndexLayout__ArgProps
  }
);

export default PlasmicPagesBlogIndexLayout;
/* prettier-ignore-end */
