/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 77YCnrwhevb2XmBSeMeRKC
export const unnamedDataToken = "";

export const field: any = (() => {
  try {
    return undefined;
  } catch (e) {
    return undefined;
  }
})();

export const title = "";
