/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 77YCnrwhevb2XmBSeMeRKC
// Component: Mj-04DmSzVe7

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import CustomHeader from "../../CustomHeader"; // plasmic-import: lVLsklxwqNh2/component
import CustomFooter from "../../CustomFooter"; // plasmic-import: dDACK3Z9VKbB/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 77YCnrwhevb2XmBSeMeRKC/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 77YCnrwhevb2XmBSeMeRKC/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 77YCnrwhevb2XmBSeMeRKC/projectcss
import sty from "./PlasmicProjectPostLayout.module.css"; // plasmic-import: Mj-04DmSzVe7/css

createPlasmicElementProxy;

export type PlasmicProjectPostLayout__VariantMembers = {};
export type PlasmicProjectPostLayout__VariantsArgs = {};
type VariantPropType = keyof PlasmicProjectPostLayout__VariantsArgs;
export const PlasmicProjectPostLayout__VariantProps =
  new Array<VariantPropType>();

export type PlasmicProjectPostLayout__ArgsType = {
  contentSlot?: React.ReactNode;
  title?: string;
  coverImage?: React.ComponentProps<typeof PlasmicImg__>["src"];
  coolnessFactor?: number;
};
type ArgPropType = keyof PlasmicProjectPostLayout__ArgsType;
export const PlasmicProjectPostLayout__ArgProps = new Array<ArgPropType>(
  "contentSlot",
  "title",
  "coverImage",
  "coolnessFactor"
);

export type PlasmicProjectPostLayout__OverridesType = {
  root?: Flex__<"div">;
  customHeader?: Flex__<typeof CustomHeader>;
  freeBox?: Flex__<"div">;
  img?: Flex__<typeof PlasmicImg__>;
  text?: Flex__<"div">;
  customFooter?: Flex__<typeof CustomFooter>;
};

export interface DefaultProjectPostLayoutProps {
  contentSlot?: React.ReactNode;
  title?: string;
  coverImage?: React.ComponentProps<typeof PlasmicImg__>["src"];
  coolnessFactor?: number;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicProjectPostLayout__RenderFunc(props: {
  variants: PlasmicProjectPostLayout__VariantsArgs;
  args: PlasmicProjectPostLayout__ArgsType;
  overrides: PlasmicProjectPostLayout__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {
          title: "Title"
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
    >
      <CustomHeader
        data-plasmic-name={"customHeader"}
        data-plasmic-override={overrides.customHeader}
        className={classNames("__wab_instance", sty.customHeader)}
      />

      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames(projectcss.all, sty.freeBox)}
      >
        <PlasmicImg__
          data-plasmic-name={"img"}
          data-plasmic-override={overrides.img}
          alt={""}
          className={classNames(sty.img)}
          displayHeight={"auto"}
          displayMaxHeight={"none"}
          displayMaxWidth={"100%"}
          displayMinHeight={"0"}
          displayMinWidth={"0"}
          displayWidth={"50%"}
          loading={"lazy"}
        />

        <div
          data-plasmic-name={"text"}
          data-plasmic-override={overrides.text}
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text
          )}
        >
          <React.Fragment>{$props.title}</React.Fragment>
        </div>
        {renderPlasmicSlot({
          defaultContents: null,
          value: args.contentSlot
        })}
      </div>
      <CustomFooter
        data-plasmic-name={"customFooter"}
        data-plasmic-override={overrides.customFooter}
        className={classNames("__wab_instance", sty.customFooter)}
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "customHeader", "freeBox", "img", "text", "customFooter"],
  customHeader: ["customHeader"],
  freeBox: ["freeBox", "img", "text"],
  img: ["img"],
  text: ["text"],
  customFooter: ["customFooter"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  customHeader: typeof CustomHeader;
  freeBox: "div";
  img: typeof PlasmicImg__;
  text: "div";
  customFooter: typeof CustomFooter;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicProjectPostLayout__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicProjectPostLayout__VariantsArgs;
    args?: PlasmicProjectPostLayout__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicProjectPostLayout__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicProjectPostLayout__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicProjectPostLayout__ArgProps,
          internalVariantPropNames: PlasmicProjectPostLayout__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicProjectPostLayout__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicProjectPostLayout";
  } else {
    func.displayName = `PlasmicProjectPostLayout.${nodeName}`;
  }
  return func;
}

export const PlasmicProjectPostLayout = Object.assign(
  // Top-level PlasmicProjectPostLayout renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    customHeader: makeNodeComponent("customHeader"),
    freeBox: makeNodeComponent("freeBox"),
    img: makeNodeComponent("img"),
    text: makeNodeComponent("text"),
    customFooter: makeNodeComponent("customFooter"),

    // Metadata about props expected for PlasmicProjectPostLayout
    internalVariantProps: PlasmicProjectPostLayout__VariantProps,
    internalArgProps: PlasmicProjectPostLayout__ArgProps
  }
);

export default PlasmicProjectPostLayout;
/* prettier-ignore-end */
