/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 77YCnrwhevb2XmBSeMeRKC
// Component: i4Mn9_jiO7iS

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import CustomHeader from "../../CustomHeader"; // plasmic-import: lVLsklxwqNh2/component
import CustomFooter from "../../CustomFooter"; // plasmic-import: dDACK3Z9VKbB/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 77YCnrwhevb2XmBSeMeRKC/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 77YCnrwhevb2XmBSeMeRKC/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 77YCnrwhevb2XmBSeMeRKC/projectcss
import sty from "./PlasmicProjectIndexLayout.module.css"; // plasmic-import: i4Mn9_jiO7iS/css

createPlasmicElementProxy;

export type PlasmicProjectIndexLayout__VariantMembers = {};
export type PlasmicProjectIndexLayout__VariantsArgs = {};
type VariantPropType = keyof PlasmicProjectIndexLayout__VariantsArgs;
export const PlasmicProjectIndexLayout__VariantProps =
  new Array<VariantPropType>();

export type PlasmicProjectIndexLayout__ArgsType = {
  projectListSlot?: React.ReactNode;
};
type ArgPropType = keyof PlasmicProjectIndexLayout__ArgsType;
export const PlasmicProjectIndexLayout__ArgProps = new Array<ArgPropType>(
  "projectListSlot"
);

export type PlasmicProjectIndexLayout__OverridesType = {
  root?: Flex__<"div">;
  customHeader?: Flex__<typeof CustomHeader>;
  customFooter?: Flex__<typeof CustomFooter>;
};

export interface DefaultProjectIndexLayoutProps {
  projectListSlot?: React.ReactNode;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicProjectIndexLayout__RenderFunc(props: {
  variants: PlasmicProjectIndexLayout__VariantsArgs;
  args: PlasmicProjectIndexLayout__ArgsType;
  overrides: PlasmicProjectIndexLayout__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
    >
      <CustomHeader
        data-plasmic-name={"customHeader"}
        data-plasmic-override={overrides.customHeader}
        className={classNames("__wab_instance", sty.customHeader)}
      />

      <div className={classNames(projectcss.all, sty.freeBox__heaIv)}>
        {renderPlasmicSlot({
          defaultContents: (
            <React.Fragment>
              <div className={classNames(projectcss.all, sty.freeBox__aNFnU)} />

              <div className={classNames(projectcss.all, sty.freeBox__hEeJv)} />
            </React.Fragment>
          ),
          value: args.projectListSlot
        })}
      </div>
      <div className={classNames(projectcss.all, sty.freeBox__vLt1W)} />

      <CustomFooter
        data-plasmic-name={"customFooter"}
        data-plasmic-override={overrides.customFooter}
        className={classNames("__wab_instance", sty.customFooter)}
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "customHeader", "customFooter"],
  customHeader: ["customHeader"],
  customFooter: ["customFooter"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  customHeader: typeof CustomHeader;
  customFooter: typeof CustomFooter;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicProjectIndexLayout__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicProjectIndexLayout__VariantsArgs;
    args?: PlasmicProjectIndexLayout__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicProjectIndexLayout__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicProjectIndexLayout__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicProjectIndexLayout__ArgProps,
          internalVariantPropNames: PlasmicProjectIndexLayout__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicProjectIndexLayout__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicProjectIndexLayout";
  } else {
    func.displayName = `PlasmicProjectIndexLayout.${nodeName}`;
  }
  return func;
}

export const PlasmicProjectIndexLayout = Object.assign(
  // Top-level PlasmicProjectIndexLayout renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    customHeader: makeNodeComponent("customHeader"),
    customFooter: makeNodeComponent("customFooter"),

    // Metadata about props expected for PlasmicProjectIndexLayout
    internalVariantProps: PlasmicProjectIndexLayout__VariantProps,
    internalArgProps: PlasmicProjectIndexLayout__ArgProps
  }
);

export default PlasmicProjectIndexLayout;
/* prettier-ignore-end */
