/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 77YCnrwhevb2XmBSeMeRKC
// Component: dDACK3Z9VKbB

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 77YCnrwhevb2XmBSeMeRKC/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 77YCnrwhevb2XmBSeMeRKC/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 77YCnrwhevb2XmBSeMeRKC/projectcss
import sty from "./PlasmicCustomFooter.module.css"; // plasmic-import: dDACK3Z9VKbB/css

createPlasmicElementProxy;

export type PlasmicCustomFooter__VariantMembers = {};
export type PlasmicCustomFooter__VariantsArgs = {};
type VariantPropType = keyof PlasmicCustomFooter__VariantsArgs;
export const PlasmicCustomFooter__VariantProps = new Array<VariantPropType>();

export type PlasmicCustomFooter__ArgsType = {};
type ArgPropType = keyof PlasmicCustomFooter__ArgsType;
export const PlasmicCustomFooter__ArgProps = new Array<ArgPropType>();

export type PlasmicCustomFooter__OverridesType = {
  copyright2026AsherEdwards?: Flex__<"div">;
};

export interface DefaultCustomFooterProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicCustomFooter__RenderFunc(props: {
  variants: PlasmicCustomFooter__VariantsArgs;
  args: PlasmicCustomFooter__ArgsType;
  overrides: PlasmicCustomFooter__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"copyright2026AsherEdwards"}
      data-plasmic-override={overrides.copyright2026AsherEdwards}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.__wab_text,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.copyright2026AsherEdwards
      )}
    >
      {"Copyright 2026 Asher Edwards"}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  copyright2026AsherEdwards: ["copyright2026AsherEdwards"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  copyright2026AsherEdwards: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCustomFooter__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCustomFooter__VariantsArgs;
    args?: PlasmicCustomFooter__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicCustomFooter__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicCustomFooter__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCustomFooter__ArgProps,
          internalVariantPropNames: PlasmicCustomFooter__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCustomFooter__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "copyright2026AsherEdwards") {
    func.displayName = "PlasmicCustomFooter";
  } else {
    func.displayName = `PlasmicCustomFooter.${nodeName}`;
  }
  return func;
}

export const PlasmicCustomFooter = Object.assign(
  // Top-level PlasmicCustomFooter renders the root element
  makeNodeComponent("copyright2026AsherEdwards"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicCustomFooter
    internalVariantProps: PlasmicCustomFooter__VariantProps,
    internalArgProps: PlasmicCustomFooter__ArgProps
  }
);

export default PlasmicCustomFooter;
/* prettier-ignore-end */
