/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 77YCnrwhevb2XmBSeMeRKC
// Component: TS8wfnEFQi2m

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import PageSupportCustomHeader from "../../PageSupport/PageSupportCustomHeader"; // plasmic-import: lVLsklxwqNh2/component
import PageSupportCustomFooter from "../../PageSupport/PageSupportCustomFooter"; // plasmic-import: dDACK3Z9VKbB/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 77YCnrwhevb2XmBSeMeRKC/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 77YCnrwhevb2XmBSeMeRKC/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 77YCnrwhevb2XmBSeMeRKC/projectcss
import sty from "./PlasmicPagesBlogPostLayout.module.css"; // plasmic-import: TS8wfnEFQi2m/css

createPlasmicElementProxy;

export type PlasmicPagesBlogPostLayout__VariantMembers = {};
export type PlasmicPagesBlogPostLayout__VariantsArgs = {};
type VariantPropType = keyof PlasmicPagesBlogPostLayout__VariantsArgs;
export const PlasmicPagesBlogPostLayout__VariantProps =
  new Array<VariantPropType>();

export type PlasmicPagesBlogPostLayout__ArgsType = {
  contentSlot?: React.ReactNode;
  title?: string;
  date?: any;
  coverImage?: React.ComponentProps<typeof PlasmicImg__>["src"];
};
type ArgPropType = keyof PlasmicPagesBlogPostLayout__ArgsType;
export const PlasmicPagesBlogPostLayout__ArgProps = new Array<ArgPropType>(
  "contentSlot",
  "title",
  "date",
  "coverImage"
);

export type PlasmicPagesBlogPostLayout__OverridesType = {
  root?: Flex__<"div">;
  pageSupportCustomHeader?: Flex__<typeof PageSupportCustomHeader>;
  img?: Flex__<typeof PlasmicImg__>;
  h1?: Flex__<"h1">;
  pageSupportCustomFooter?: Flex__<typeof PageSupportCustomFooter>;
};

export interface DefaultPagesBlogPostLayoutProps {
  contentSlot?: React.ReactNode;
  title?: string;
  date?: any;
  coverImage?: React.ComponentProps<typeof PlasmicImg__>["src"];
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicPagesBlogPostLayout__RenderFunc(props: {
  variants: PlasmicPagesBlogPostLayout__VariantsArgs;
  args: PlasmicPagesBlogPostLayout__ArgsType;
  overrides: PlasmicPagesBlogPostLayout__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {
          title: "Title"
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
    >
      <PageSupportCustomHeader
        data-plasmic-name={"pageSupportCustomHeader"}
        data-plasmic-override={overrides.pageSupportCustomHeader}
        className={classNames("__wab_instance", sty.pageSupportCustomHeader)}
      />

      <div className={classNames(projectcss.all, sty.freeBox__luIhi)}>
        <PlasmicImg__
          data-plasmic-name={"img"}
          data-plasmic-override={overrides.img}
          alt={""}
          className={classNames(sty.img)}
          displayHeight={"auto"}
          displayMaxHeight={"none"}
          displayMaxWidth={"100%"}
          displayMinHeight={"0"}
          displayMinWidth={"0"}
          displayWidth={"50%"}
          loading={"lazy"}
          src={(() => {
            try {
              return $props.coverImage;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })()}
        />

        <h1
          data-plasmic-name={"h1"}
          data-plasmic-override={overrides.h1}
          className={classNames(
            projectcss.all,
            projectcss.h1,
            projectcss.h1__77YCn,
            projectcss.__wab_text,
            sty.h1,
            ""
          )}
        >
          <React.Fragment>{$props.title}</React.Fragment>
        </h1>
        {renderPlasmicSlot({
          defaultContents: null,
          value: args.contentSlot
        })}
      </div>
      <div className={classNames(projectcss.all, sty.freeBox__udkDh)} />

      <PageSupportCustomFooter
        data-plasmic-name={"pageSupportCustomFooter"}
        data-plasmic-override={overrides.pageSupportCustomFooter}
        className={classNames("__wab_instance", sty.pageSupportCustomFooter)}
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "pageSupportCustomHeader",
    "img",
    "h1",
    "pageSupportCustomFooter"
  ],

  pageSupportCustomHeader: ["pageSupportCustomHeader"],
  img: ["img"],
  h1: ["h1"],
  pageSupportCustomFooter: ["pageSupportCustomFooter"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  pageSupportCustomHeader: typeof PageSupportCustomHeader;
  img: typeof PlasmicImg__;
  h1: "h1";
  pageSupportCustomFooter: typeof PageSupportCustomFooter;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPagesBlogPostLayout__OverridesType,
  DescendantsType<T>
>;

type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPagesBlogPostLayout__VariantsArgs;
    args?: PlasmicPagesBlogPostLayout__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicPagesBlogPostLayout__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicPagesBlogPostLayout__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicPagesBlogPostLayout__ArgProps,
          internalVariantPropNames: PlasmicPagesBlogPostLayout__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicPagesBlogPostLayout__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPagesBlogPostLayout";
  } else {
    func.displayName = `PlasmicPagesBlogPostLayout.${nodeName}`;
  }
  return func;
}

export const PlasmicPagesBlogPostLayout = Object.assign(
  // Top-level PlasmicPagesBlogPostLayout renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    pageSupportCustomHeader: makeNodeComponent("pageSupportCustomHeader"),
    img: makeNodeComponent("img"),
    h1: makeNodeComponent("h1"),
    pageSupportCustomFooter: makeNodeComponent("pageSupportCustomFooter"),

    // Metadata about props expected for PlasmicPagesBlogPostLayout
    internalVariantProps: PlasmicPagesBlogPostLayout__VariantProps,
    internalArgProps: PlasmicPagesBlogPostLayout__ArgProps
  }
);

export default PlasmicPagesBlogPostLayout;
/* prettier-ignore-end */
