/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 77YCnrwhevb2XmBSeMeRKC
// Component: dDACK3Z9VKbB

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 77YCnrwhevb2XmBSeMeRKC/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 77YCnrwhevb2XmBSeMeRKC/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 77YCnrwhevb2XmBSeMeRKC/projectcss
import sty from "./PlasmicPageSupportCustomFooter.module.css"; // plasmic-import: dDACK3Z9VKbB/css

createPlasmicElementProxy;

export type PlasmicPageSupportCustomFooter__VariantMembers = {};
export type PlasmicPageSupportCustomFooter__VariantsArgs = {};
type VariantPropType = keyof PlasmicPageSupportCustomFooter__VariantsArgs;
export const PlasmicPageSupportCustomFooter__VariantProps =
  new Array<VariantPropType>();

export type PlasmicPageSupportCustomFooter__ArgsType = {};
type ArgPropType = keyof PlasmicPageSupportCustomFooter__ArgsType;
export const PlasmicPageSupportCustomFooter__ArgProps =
  new Array<ArgPropType>();

export type PlasmicPageSupportCustomFooter__OverridesType = {
  root?: Flex__<"div">;
  copyright2026AsherEdwards?: Flex__<"div">;
};

export interface DefaultPageSupportCustomFooterProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicPageSupportCustomFooter__RenderFunc(props: {
  variants: PlasmicPageSupportCustomFooter__VariantsArgs;
  args: PlasmicPageSupportCustomFooter__ArgsType;
  overrides: PlasmicPageSupportCustomFooter__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"copyright2026AsherEdwards"}
        data-plasmic-override={overrides.copyright2026AsherEdwards}
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.copyright2026AsherEdwards
        )}
      >
        {"Copyright 2026 Asher Edwards"}
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "copyright2026AsherEdwards"],
  copyright2026AsherEdwards: ["copyright2026AsherEdwards"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  copyright2026AsherEdwards: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPageSupportCustomFooter__OverridesType,
  DescendantsType<T>
>;

type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPageSupportCustomFooter__VariantsArgs;
    args?: PlasmicPageSupportCustomFooter__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicPageSupportCustomFooter__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicPageSupportCustomFooter__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicPageSupportCustomFooter__ArgProps,
          internalVariantPropNames: PlasmicPageSupportCustomFooter__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicPageSupportCustomFooter__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPageSupportCustomFooter";
  } else {
    func.displayName = `PlasmicPageSupportCustomFooter.${nodeName}`;
  }
  return func;
}

export const PlasmicPageSupportCustomFooter = Object.assign(
  // Top-level PlasmicPageSupportCustomFooter renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    copyright2026AsherEdwards: makeNodeComponent("copyright2026AsherEdwards"),

    // Metadata about props expected for PlasmicPageSupportCustomFooter
    internalVariantProps: PlasmicPageSupportCustomFooter__VariantProps,
    internalArgProps: PlasmicPageSupportCustomFooter__ArgProps
  }
);

export default PlasmicPageSupportCustomFooter;
/* prettier-ignore-end */
