/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 77YCnrwhevb2XmBSeMeRKC

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsyjiIakDgcfVe } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: YjiIAKDgcfVE/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsyjiIakDgcfVe
});
