/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 77YCnrwhevb2XmBSeMeRKC
// Component: f7_eeq1__cMs

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import CustomHeader from "../../CustomHeader"; // plasmic-import: lVLsklxwqNh2/component
import CustomFooter from "../../CustomFooter"; // plasmic-import: dDACK3Z9VKbB/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 77YCnrwhevb2XmBSeMeRKC/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 77YCnrwhevb2XmBSeMeRKC/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 77YCnrwhevb2XmBSeMeRKC/projectcss
import sty from "./Plasmic_404.module.css"; // plasmic-import: f7_eeq1__cMs/css

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export type PageCtx = {
  pageRoute: string;
  pagePath: string;
  params: Record<string, string | string[] | undefined>;
  query: Record<string, string | string[] | undefined>;
};

export function generateDynamicMetadata($q: any, $ctx: PageCtx) {
  return {
    openGraph: {},
    twitter: {
      card: "summary" as const
    }
  };
}

createPlasmicElementProxy;

export type Plasmic_404__VariantMembers = {};
export type Plasmic_404__VariantsArgs = {};
type VariantPropType = keyof Plasmic_404__VariantsArgs;
export const Plasmic_404__VariantProps = new Array<VariantPropType>();

export type Plasmic_404__ArgsType = {};
type ArgPropType = keyof Plasmic_404__ArgsType;
export const Plasmic_404__ArgProps = new Array<ArgPropType>();

export type Plasmic_404__OverridesType = {
  root?: Flex__<"div">;
  freeBox?: Flex__<"div">;
  customHeader?: Flex__<typeof CustomHeader>;
  text?: Flex__<"div">;
  back?: Flex__<"a"> & Partial<LinkProps>;
  customFooter?: Flex__<typeof CustomFooter>;
};

export interface Default_404Props {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function Plasmic_404__RenderFunc(props: {
  variants: Plasmic_404__VariantsArgs;
  args: Plasmic_404__ArgsType;
  overrides: Plasmic_404__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy({}),
    $ctx as PageCtx
  );

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"freeBox"}
            data-plasmic-override={overrides.freeBox}
            className={classNames(projectcss.all, sty.freeBox)}
          >
            <CustomHeader
              data-plasmic-name={"customHeader"}
              data-plasmic-override={overrides.customHeader}
              className={classNames("__wab_instance", sty.customHeader)}
            />

            <div
              data-plasmic-name={"text"}
              data-plasmic-override={overrides.text}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text
              )}
            >
              {
                "404\nUh oh, looks like you ran into some wild unicyclers!\nWe couldn't find what you were looking for"
              }
            </div>
            <PlasmicLink__
              data-plasmic-name={"back"}
              data-plasmic-override={overrides.back}
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.a__77YCn,
                projectcss.__wab_text,
                sty.back
              )}
              component={Link}
              href={`/`}
              legacyBehavior={false}
              platform={"nextjs"}
            >
              {"\u21a9Back"}
            </PlasmicLink__>
            <CustomFooter
              data-plasmic-name={"customFooter"}
              data-plasmic-override={overrides.customFooter}
              className={classNames("__wab_instance", sty.customFooter)}
            />
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "freeBox", "customHeader", "text", "back", "customFooter"],
  freeBox: ["freeBox", "customHeader", "text", "back", "customFooter"],
  customHeader: ["customHeader"],
  text: ["text"],
  back: ["back"],
  customFooter: ["customFooter"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  freeBox: "div";
  customHeader: typeof CustomHeader;
  text: "div";
  back: "a";
  customFooter: typeof CustomFooter;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  Plasmic_404__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: Plasmic_404__VariantsArgs;
    args?: Plasmic_404__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<Plasmic_404__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<Plasmic_404__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: Plasmic_404__ArgProps,
          internalVariantPropNames: Plasmic_404__VariantProps
        }),
      [props, nodeName]
    );
    return Plasmic_404__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "Plasmic_404";
  } else {
    func.displayName = `Plasmic_404.${nodeName}`;
  }
  return func;
}

export const Plasmic_404 = Object.assign(
  // Top-level Plasmic_404 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    customHeader: makeNodeComponent("customHeader"),
    text: makeNodeComponent("text"),
    back: makeNodeComponent("back"),
    customFooter: makeNodeComponent("customFooter"),

    // Metadata about props expected for Plasmic_404
    internalVariantProps: Plasmic_404__VariantProps,
    internalArgProps: Plasmic_404__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/404",
      pagePath: "/404",
      params: {},
      query: {}
    })
  }
);

export default Plasmic_404;
/* prettier-ignore-end */
