/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 77YCnrwhevb2XmBSeMeRKC
// Component: SRR7d6afVmf-

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import CustomHeader from "../../CustomHeader"; // plasmic-import: lVLsklxwqNh2/component
import { Reveal } from "@plasmicpkgs/react-awesome-reveal";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 77YCnrwhevb2XmBSeMeRKC/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 77YCnrwhevb2XmBSeMeRKC/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 77YCnrwhevb2XmBSeMeRKC/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: SRR7d6afVmf-/css

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export type PageCtx = {
  pageRoute: string;
  pagePath: string;
  params: Record<string, string | string[] | undefined>;
  query: Record<string, string | string[] | undefined>;
};

export function generateDynamicMetadata($q: any, $ctx: PageCtx) {
  return {
    openGraph: {},
    twitter: {
      card: "summary" as const
    }
  };
}

createPlasmicElementProxy;

export type PlasmicHomepage__VariantMembers = {};
export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {
  skillTrackSlot?: React.ReactNode;
  topThreeProjects?: React.ReactNode;
};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>(
  "skillTrackSlot",
  "topThreeProjects"
);

export type PlasmicHomepage__OverridesType = {
  root?: Flex__<"div">;
  customHeader?: Flex__<typeof CustomHeader>;
  reveal?: Flex__<typeof Reveal>;
  type?: Flex__<"div">;
  type2?: Flex__<"div">;
  type3?: Flex__<"div">;
  type4?: Flex__<"div">;
  img?: Flex__<typeof PlasmicImg__>;
};

export interface DefaultHomepageProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy({}),
    $ctx as PageCtx
  );

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <CustomHeader
            data-plasmic-name={"customHeader"}
            data-plasmic-override={overrides.customHeader}
            className={classNames("__wab_instance", sty.customHeader)}
          />

          <section className={classNames(projectcss.all, sty.section__bmLR)}>
            <h1
              className={classNames(
                projectcss.all,
                projectcss.h1,
                projectcss.h1__77YCn,
                projectcss.__wab_text,
                sty.h1__qsOcm
              )}
              onScroll={async event => {
                const $steps = {};

                $steps["runInteractionProp"] = true
                  ? (() => {
                      const actionArgs = {};
                      return (({ eventRef, args }) => {
                        return eventRef?.(...(args ?? []));
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["runInteractionProp"] != null &&
                  typeof $steps["runInteractionProp"] === "object" &&
                  typeof $steps["runInteractionProp"].then === "function"
                ) {
                  $steps["runInteractionProp"] =
                    await $steps["runInteractionProp"];
                }
              }}
            >
              {"Magic"}
            </h1>
            <div className={classNames(projectcss.all, sty.freeBox__eopKl)} />

            <section
              className={classNames(projectcss.all, sty.section___7ZwnX)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__pXwg9)} />

              <Reveal
                data-plasmic-name={"reveal"}
                data-plasmic-override={overrides.reveal}
                cascade={true}
                className={classNames("__wab_instance", sty.reveal)}
                delay={100}
                triggerOnce={true}
              >
                <div
                  data-plasmic-name={"type"}
                  data-plasmic-override={overrides.type}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.type
                  )}
                >
                  {"Should"}
                </div>
                <div
                  data-plasmic-name={"type2"}
                  data-plasmic-override={overrides.type2}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.type2
                  )}
                >
                  {"Not"}
                </div>
                <div
                  data-plasmic-name={"type3"}
                  data-plasmic-override={overrides.type3}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.type3
                  )}
                >
                  {"Be"}
                </div>
                <div
                  data-plasmic-name={"type4"}
                  data-plasmic-override={overrides.type4}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.type4
                  )}
                >
                  {"Impossible"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ttbXz
                  )}
                >
                  <React.Fragment>
                    <span
                      className={
                        "plasmic_default__all plasmic_default__span plasmic_default__span__77YCn"
                      }
                      style={{ fontStyle: "italic" }}
                    >
                      {
                        '"Any sufficiently advanced technology is indistinguishable from magic"'
                      }
                    </span>
                  </React.Fragment>
                </div>
              </Reveal>
              <div className={classNames(projectcss.all, sty.freeBox__u1Rol)} />

              <div className={classNames(projectcss.all, sty.freeBox__dvF3Y)}>
                <h1
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.h1__77YCn,
                    projectcss.__wab_text,
                    sty.h1__cTcWp
                  )}
                  id={"about"}
                >
                  {"About me"}
                </h1>
                <div className={classNames(projectcss.all, sty.freeBox__xZyei)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__davsf)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__fcdo0
                      )}
                    >
                      {
                        "I am a design engineer @ Colorado School of Mines, combining my intricate knowledge of mechanical, electrical, and computer engineering into products that focus on people and making the solution magical, not technical.\n\nI like creating fun project that don't always have an obvious purpose, but they entertain many and bring joy."
                      }
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__apW6B)}
                  >
                    <PlasmicImg__
                      data-plasmic-name={"img"}
                      data-plasmic-override={overrides.img}
                      alt={""}
                      className={classNames(sty.img)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"50%"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/fiat_novum/images/userImageLinkedInJpg.jpg",
                        fullWidth: 1307,
                        fullHeight: 1743,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                </div>
              </div>
            </section>
          </section>
          <section
            className={classNames(
              projectcss.all,
              sty.section__c0Fox,
              "marquee-container"
            )}
          >
            {renderPlasmicSlot({
              defaultContents: null,
              value: args.skillTrackSlot
            })}
          </section>
          <section className={classNames(projectcss.all, sty.section__fhLkD)}>
            <div className={classNames(projectcss.all, sty.freeBox__vzaZi)} />

            <h1
              className={classNames(
                projectcss.all,
                projectcss.h1,
                projectcss.h1__77YCn,
                projectcss.__wab_text,
                sty.h1__nC7W
              )}
              id={"projects"}
            >
              {"Projects"}
            </h1>
            <div className={classNames(projectcss.all, sty.freeBox__q9MBb)}>
              {renderPlasmicSlot({
                defaultContents: "",
                value: args.topThreeProjects,
                className: classNames(sty.slotTargetTopThreeProjects)
              })}
            </div>
          </section>
          <section className={classNames(projectcss.all, sty.section__utLj)}>
            <h1
              className={classNames(
                projectcss.all,
                projectcss.h1,
                projectcss.h1__77YCn,
                projectcss.__wab_text,
                sty.h1__gCsO
              )}
              id={"contact"}
            >
              {"Contact"}
            </h1>
            <div className={classNames(projectcss.all, sty.freeBox__jtTb)}>
              <div className={classNames(projectcss.all, sty.freeBox__bIgf)}>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.a__77YCn,
                    projectcss.__wab_text,
                    sty.link__lHhq
                  )}
                  component={Link}
                  href={"mailto:asher@fiatnovum.com"}
                  legacyBehavior={false}
                  platform={"nextjs"}
                >
                  {"asher@fiatnovum.com"}
                </PlasmicLink__>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox___6Tem)}>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.a__77YCn,
                    projectcss.__wab_text,
                    sty.link__cnSr1
                  )}
                  component={Link}
                  href={"https://www.linkedin.com/in/asher-j-edwards1/"}
                  legacyBehavior={false}
                  platform={"nextjs"}
                >
                  {"LinkedIn: asher-j-edwards1"}
                </PlasmicLink__>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__b2X27)}>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.a__77YCn,
                    projectcss.__wab_text,
                    sty.link___6OPty
                  )}
                  component={Link}
                  href={"https://www.youtube.com/@FiatNovumEngineering"}
                  legacyBehavior={false}
                  platform={"nextjs"}
                >
                  {"Youtube: @FiatNovumEngineering"}
                </PlasmicLink__>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__ayIKe)}>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.a__77YCn,
                    projectcss.__wab_text,
                    sty.link__noZs
                  )}
                  component={Link}
                  href={"https://github.com/techy-robot"}
                  legacyBehavior={false}
                  platform={"nextjs"}
                >
                  {"GitHub: techy-robot"}
                </PlasmicLink__>
              </div>
            </div>
          </section>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "customHeader",
    "reveal",
    "type",
    "type2",
    "type3",
    "type4",
    "img"
  ],
  customHeader: ["customHeader"],
  reveal: ["reveal", "type", "type2", "type3", "type4"],
  type: ["type"],
  type2: ["type2"],
  type3: ["type3"],
  type4: ["type4"],
  img: ["img"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  customHeader: typeof CustomHeader;
  reveal: typeof Reveal;
  type: "div";
  type2: "div";
  type3: "div";
  type4: "div";
  img: typeof PlasmicImg__;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicHomepage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    customHeader: makeNodeComponent("customHeader"),
    reveal: makeNodeComponent("reveal"),
    type: makeNodeComponent("type"),
    type2: makeNodeComponent("type2"),
    type3: makeNodeComponent("type3"),
    type4: makeNodeComponent("type4"),
    img: makeNodeComponent("img"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/",
      pagePath: "/",
      params: {},
      query: {}
    })
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
