/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 77YCnrwhevb2XmBSeMeRKC
// Component: Mj-04DmSzVe7

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import PageSupportCustomHeader from "../../PageSupport/PageSupportCustomHeader"; // plasmic-import: lVLsklxwqNh2/component
import Breadcrumbs from "@/components/UI/Breadcrumbs"; // plasmic-import: QM8Fl9mappeA/codeComponent
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 77YCnrwhevb2XmBSeMeRKC/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 77YCnrwhevb2XmBSeMeRKC/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicPagesProjectPostLayout.module.css"; // plasmic-import: Mj-04DmSzVe7/css

createPlasmicElementProxy;

export type PlasmicPagesProjectPostLayout__VariantMembers = {};
export type PlasmicPagesProjectPostLayout__VariantsArgs = {};
type VariantPropType = keyof PlasmicPagesProjectPostLayout__VariantsArgs;
export const PlasmicPagesProjectPostLayout__VariantProps =
  new Array<VariantPropType>();

export type PlasmicPagesProjectPostLayout__ArgsType = {
  contentSlot?: React.ReactNode;
  title?: string;
  coverImage?: React.ComponentProps<typeof PlasmicImg__>["src"];
  coolnessFactor?: number;
};
type ArgPropType = keyof PlasmicPagesProjectPostLayout__ArgsType;
export const PlasmicPagesProjectPostLayout__ArgProps = new Array<ArgPropType>(
  "contentSlot",
  "title",
  "coverImage",
  "coolnessFactor"
);

export type PlasmicPagesProjectPostLayout__OverridesType = {
  root?: Flex__<"div">;
  pageSupportCustomHeader?: Flex__<typeof PageSupportCustomHeader>;
  breadcrumbs?: Flex__<typeof Breadcrumbs>;
  freeBox?: Flex__<"div">;
  img?: Flex__<typeof PlasmicImg__>;
  h1?: Flex__<"h1">;
};

export interface DefaultPagesProjectPostLayoutProps {
  contentSlot?: React.ReactNode;
  title?: string;
  coverImage?: React.ComponentProps<typeof PlasmicImg__>["src"];
  coolnessFactor?: number;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicPagesProjectPostLayout__RenderFunc(props: {
  variants: PlasmicPagesProjectPostLayout__VariantsArgs;
  args: PlasmicPagesProjectPostLayout__ArgsType;
  overrides: PlasmicPagesProjectPostLayout__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {
          title: "Title"
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "all",
        "root_reset_77YCnrwhevb2XmBSeMeRKC",
        "plasmic_default_styles",
        "plasmic_mixins",
        styleTokensClassNames,
        sty.root
      )}
    >
      <PageSupportCustomHeader
        data-plasmic-name={"pageSupportCustomHeader"}
        data-plasmic-override={overrides.pageSupportCustomHeader}
        className={classNames("__wab_instance", sty.pageSupportCustomHeader)}
      />

      <Breadcrumbs
        data-plasmic-name={"breadcrumbs"}
        data-plasmic-override={overrides.breadcrumbs}
        className={classNames("__wab_instance", sty.breadcrumbs)}
        pageTitle={(() => {
          try {
            return $props.title;
          } catch (e) {
            if (
              e instanceof TypeError ||
              e?.plasmicType === "PlasmicUndefinedDataError"
            ) {
              return undefined;
            }
            throw e;
          }
        })()}
      />

      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames("all", sty.freeBox)}
      >
        <PlasmicImg__
          data-plasmic-name={"img"}
          data-plasmic-override={overrides.img}
          alt={""}
          className={classNames(sty.img)}
          displayHeight={"auto"}
          displayMaxHeight={"none"}
          displayMaxWidth={"none"}
          displayMinHeight={"0"}
          displayMinWidth={"0"}
          displayWidth={"100%"}
          loading={"lazy"}
          src={(() => {
            try {
              return $props.coverImage;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })()}
          width={""}
        />

        <h1
          data-plasmic-name={"h1"}
          data-plasmic-override={overrides.h1}
          className={classNames("all", "h1", "h1__77YCn", "__wab_text", sty.h1)}
        >
          <React.Fragment>{$props.title}</React.Fragment>
        </h1>
        {renderPlasmicSlot({
          defaultContents: null,
          value: args.contentSlot
        })}
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "pageSupportCustomHeader",
    "breadcrumbs",
    "freeBox",
    "img",
    "h1"
  ],
  pageSupportCustomHeader: ["pageSupportCustomHeader"],
  breadcrumbs: ["breadcrumbs"],
  freeBox: ["freeBox", "img", "h1"],
  img: ["img"],
  h1: ["h1"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  pageSupportCustomHeader: typeof PageSupportCustomHeader;
  breadcrumbs: typeof Breadcrumbs;
  freeBox: "div";
  img: typeof PlasmicImg__;
  h1: "h1";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPagesProjectPostLayout__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPagesProjectPostLayout__VariantsArgs;
    args?: PlasmicPagesProjectPostLayout__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicPagesProjectPostLayout__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicPagesProjectPostLayout__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicPagesProjectPostLayout__ArgProps,
          internalVariantPropNames: PlasmicPagesProjectPostLayout__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicPagesProjectPostLayout__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPagesProjectPostLayout";
  } else {
    func.displayName = `PlasmicPagesProjectPostLayout.${nodeName}`;
  }
  return func;
}

export const PlasmicPagesProjectPostLayout = Object.assign(
  // Top-level PlasmicPagesProjectPostLayout renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    pageSupportCustomHeader: makeNodeComponent("pageSupportCustomHeader"),
    breadcrumbs: makeNodeComponent("breadcrumbs"),
    freeBox: makeNodeComponent("freeBox"),
    img: makeNodeComponent("img"),
    h1: makeNodeComponent("h1"),

    // Metadata about props expected for PlasmicPagesProjectPostLayout
    internalVariantProps: PlasmicPagesProjectPostLayout__VariantProps,
    internalArgProps: PlasmicPagesProjectPostLayout__ArgProps
  }
);

export default PlasmicPagesProjectPostLayout;
/* prettier-ignore-end */
