/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 77YCnrwhevb2XmBSeMeRKC
// Component: PgD-W9uOOpoF

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { BaseComboBox } from "@plasmicpkgs/react-aria/skinny/registerComboBox";
import UiLabel from "../../UI/UiLabel"; // plasmic-import: V7xESUXLSQu1/component
import { BaseInput } from "@plasmicpkgs/react-aria/skinny/registerInput";
import { inputHelpers as BaseInput_Helpers } from "@plasmicpkgs/react-aria/skinny/registerInput";
import { BaseButton } from "@plasmicpkgs/react-aria/skinny/registerButton";
import UiDescription from "../../UI/UiDescription"; // plasmic-import: bvUZ48jLKi3q/component
import UiMenuPopover from "../../UI/UiMenuPopover"; // plasmic-import: fGihvQNY2l98/component
import UiMenuItem from "../../UI/UiMenuItem"; // plasmic-import: KgLjNhvdSd7Q/component
import UiMenuSection from "../../UI/UiMenuSection"; // plasmic-import: 2tPmM2UgS2Fw/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 77YCnrwhevb2XmBSeMeRKC/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 77YCnrwhevb2XmBSeMeRKC/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicUiCombobox.module.css"; // plasmic-import: PgD-W9uOOpoF/css

import ChevronDownIcon from "./icons/PlasmicIcon__ChevronDown"; // plasmic-import: Y2onwRPGGLt5/icon

createPlasmicElementProxy;

export type PlasmicUiCombobox__VariantMembers = {
  type: "soft" | "plain";
};
export type PlasmicUiCombobox__VariantsArgs = {
  type?: SingleChoiceArg<"soft" | "plain">;
};
type VariantPropType = keyof PlasmicUiCombobox__VariantsArgs;
export const PlasmicUiCombobox__VariantProps = new Array<VariantPropType>(
  "type"
);

export type PlasmicUiCombobox__ArgsType = {
  isOpen?: boolean;
  onOpenChange?: (val: boolean) => void;
  value?: string;
  placeholder?: string;
  showLabel?: boolean;
  showDescription?: boolean;
  onChange?: (val: string) => void;
  autoFocus?: boolean;
  inputDisplayValue?: string;
  disabled?: boolean;
  ariaLabel?: string;
  readOnly?: boolean;
  label?: React.ReactNode;
  description?: React.ReactNode;
  items?: React.ReactNode;
};
type ArgPropType = keyof PlasmicUiCombobox__ArgsType;
export const PlasmicUiCombobox__ArgProps = new Array<ArgPropType>(
  "isOpen",
  "onOpenChange",
  "value",
  "placeholder",
  "showLabel",
  "showDescription",
  "onChange",
  "autoFocus",
  "inputDisplayValue",
  "disabled",
  "ariaLabel",
  "readOnly",
  "label",
  "description",
  "items"
);

export type PlasmicUiCombobox__OverridesType = {
  ariaComboBox?: Flex__<typeof BaseComboBox>;
  uiLabel?: Flex__<typeof UiLabel>;
  freeBox?: Flex__<"div">;
  ariaInput?: Flex__<typeof BaseInput>;
  ariaButton?: Flex__<typeof BaseButton>;
  svg?: Flex__<"svg">;
  uiDescription?: Flex__<typeof UiDescription>;
  uiMenuPopover?: Flex__<typeof UiMenuPopover>;
};

export interface DefaultUiComboboxProps {
  isOpen?: boolean;
  onOpenChange?: (val: boolean) => void;
  value?: string;
  placeholder?: string;
  showLabel?: boolean;
  showDescription?: boolean;
  onChange?: (val: string) => void;
  autoFocus?: boolean;
  inputDisplayValue?: string;
  disabled?: boolean;
  ariaLabel?: string;
  readOnly?: boolean;
  label?: React.ReactNode;
  description?: React.ReactNode;
  items?: React.ReactNode;
  type?: SingleChoiceArg<"soft" | "plain">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicUiCombobox__RenderFunc(props: {
  variants: PlasmicUiCombobox__VariantsArgs;
  args: PlasmicUiCombobox__ArgsType;
  overrides: PlasmicUiCombobox__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {
          placeholder: "Select an item",
          showLabel: true,
          showDescription: false
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "ariaComboBox.isOpen",
        type: "writable",
        variableType: "boolean",

        valueProp: "isOpen",
        onChangeProp: "onOpenChange"
      },
      {
        path: "ariaComboBox.selectedValue",
        type: "writable",
        variableType: "text",

        valueProp: "value",
        onChangeProp: "onChange"
      },
      {
        path: "type",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => $props.type
      },
      {
        path: "ariaInput.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", BaseInput_Helpers)
      }
    ],
    [$props, $ctx, $refs]
  );

  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  const [$ccVariants, setDollarCcVariants] = React.useState<
    Record<string, boolean>
  >({
    disabled: false
  });
  const updateVariant = React.useCallback(
    (changes: Record<string, boolean>) => {
      setDollarCcVariants(prev => {
        if (!Object.keys(changes).some(k => prev[k] !== changes[k])) {
          return prev;
        }
        return { ...prev, ...changes };
      });
    },
    []
  );

  return (
    <BaseComboBox
      data-plasmic-name={"ariaComboBox"}
      data-plasmic-override={overrides.ariaComboBox}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      aria-label={args.ariaLabel}
      className={classNames(
        "__wab_instance",
        "root_reset_77YCnrwhevb2XmBSeMeRKC",
        "plasmic_default_styles",
        "plasmic_mixins",
        styleTokensClassNames,
        sty.ariaComboBox,
        {
          [sty.ariaComboBoxtype_plain]: hasVariant($state, "type", "plain"),
          [sty.ariaComboBoxtype_soft]: hasVariant($state, "type", "soft")
        }
      )}
      isDisabled={args.disabled}
      isOpen={generateStateValueProp($state, ["ariaComboBox", "isOpen"])}
      onOpenChange={async (...eventArgs: any) => {
        generateStateOnChangeProp($state, ["ariaComboBox", "isOpen"]).apply(
          null,
          eventArgs
        );
      }}
      onSelectionChange={async (...eventArgs: any) => {
        generateStateOnChangeProp($state, [
          "ariaComboBox",
          "selectedValue"
        ]).apply(null, eventArgs);
      }}
      plasmicUpdateVariant={updateVariant}
      selectedKey={generateStateValueProp($state, [
        "ariaComboBox",
        "selectedValue"
      ])}
    >
      {$props.showLabel ? (
        <UiLabel
          data-plasmic-name={"uiLabel"}
          data-plasmic-override={overrides.uiLabel}
          className={classNames("__wab_instance", sty.uiLabel)}
        >
          {renderPlasmicSlot({
            defaultContents: "Label",
            value: args.label
          })}
        </UiLabel>
      ) : null}
      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames("all", sty.freeBox)}
      >
        {(() => {
          const child$Props = {
            className: classNames("__wab_instance", sty.ariaInput),
            onChange: async (...eventArgs: any) => {
              generateStateOnChangePropForCodeComponents(
                $state,
                "value",
                ["ariaInput", "value"],
                BaseInput_Helpers
              ).apply(null, eventArgs);
            },
            placeholder: args.placeholder,
            value: generateStateValueProp($state, ["ariaInput", "value"])
          };
          initializeCodeComponentStates(
            $state,
            [
              {
                name: "value",
                plasmicStateName: "ariaInput.value"
              }
            ],
            [],
            BaseInput_Helpers ?? {},
            child$Props
          );

          return (
            <BaseInput
              data-plasmic-name={"ariaInput"}
              data-plasmic-override={overrides.ariaInput}
              {...child$Props}
            />
          );
        })()}
        <BaseButton
          data-plasmic-name={"ariaButton"}
          data-plasmic-override={overrides.ariaButton}
          className={classNames("__wab_instance", sty.ariaButton)}
        >
          <ChevronDownIcon
            data-plasmic-name={"svg"}
            data-plasmic-override={overrides.svg}
            className={classNames("all", sty.svg)}
            role={"img"}
          />
        </BaseButton>
      </div>
      {$props.showDescription ? (
        <UiDescription
          data-plasmic-name={"uiDescription"}
          data-plasmic-override={overrides.uiDescription}
          className={classNames("__wab_instance", sty.uiDescription)}
        >
          {renderPlasmicSlot({
            defaultContents: "Description...",
            value: args.description
          })}
        </UiDescription>
      ) : null}
      <UiMenuPopover
        data-plasmic-name={"uiMenuPopover"}
        data-plasmic-override={overrides.uiMenuPopover}
        menuItems={renderPlasmicSlot({
          defaultContents: (
            <React.Fragment>
              <UiMenuItem label={"Item 1"} value={"item1"} />

              <UiMenuItem label={"Item 2"} value={"item2"} />

              <UiMenuItem label={"Item 3"} value={"item3"} />

              <UiMenuSection
                header={
                  <div
                    className={classNames("all", "__wab_text", sty.text__q3Izh)}
                  >
                    {"Section"}
                  </div>
                }
                items={
                  <React.Fragment>
                    <UiMenuItem
                      label={"Section Item 1"}
                      value={"section-item-1"}
                    />

                    <UiMenuItem
                      label={"Section Item 2"}
                      value={"section-item-2"}
                    />

                    <UiMenuItem
                      label={"Section Item 3"}
                      value={"section-item-3"}
                    />
                  </React.Fragment>
                }
              />
            </React.Fragment>
          ),
          value: args.items
        })}
        offset={2}
      />
    </BaseComboBox>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  ariaComboBox: [
    "ariaComboBox",
    "uiLabel",
    "freeBox",
    "ariaInput",
    "ariaButton",
    "svg",
    "uiDescription",
    "uiMenuPopover"
  ],
  uiLabel: ["uiLabel"],
  freeBox: ["freeBox", "ariaInput", "ariaButton", "svg"],
  ariaInput: ["ariaInput"],
  ariaButton: ["ariaButton", "svg"],
  svg: ["svg"],
  uiDescription: ["uiDescription"],
  uiMenuPopover: ["uiMenuPopover"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  ariaComboBox: typeof BaseComboBox;
  uiLabel: typeof UiLabel;
  freeBox: "div";
  ariaInput: typeof BaseInput;
  ariaButton: typeof BaseButton;
  svg: "svg";
  uiDescription: typeof UiDescription;
  uiMenuPopover: typeof UiMenuPopover;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicUiCombobox__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicUiCombobox__VariantsArgs;
    args?: PlasmicUiCombobox__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicUiCombobox__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicUiCombobox__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicUiCombobox__ArgProps,
          internalVariantPropNames: PlasmicUiCombobox__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicUiCombobox__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "ariaComboBox") {
    func.displayName = "PlasmicUiCombobox";
  } else {
    func.displayName = `PlasmicUiCombobox.${nodeName}`;
  }
  return func;
}

export const PlasmicUiCombobox = Object.assign(
  // Top-level PlasmicUiCombobox renders the root element
  makeNodeComponent("ariaComboBox"),
  {
    // Helper components rendering sub-elements
    uiLabel: makeNodeComponent("uiLabel"),
    freeBox: makeNodeComponent("freeBox"),
    ariaInput: makeNodeComponent("ariaInput"),
    ariaButton: makeNodeComponent("ariaButton"),
    svg: makeNodeComponent("svg"),
    uiDescription: makeNodeComponent("uiDescription"),
    uiMenuPopover: makeNodeComponent("uiMenuPopover"),

    // Metadata about props expected for PlasmicUiCombobox
    internalVariantProps: PlasmicUiCombobox__VariantProps,
    internalArgProps: PlasmicUiCombobox__ArgProps
  }
);

export default PlasmicUiCombobox;
/* prettier-ignore-end */
