/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 77YCnrwhevb2XmBSeMeRKC
// Component: lVLsklxwqNh2

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { NavigationBar } from "@plasmicpkgs/plasmic-nav";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 77YCnrwhevb2XmBSeMeRKC/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 77YCnrwhevb2XmBSeMeRKC/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 77YCnrwhevb2XmBSeMeRKC/projectcss
import sty from "./PlasmicCustomHeader.module.css"; // plasmic-import: lVLsklxwqNh2/css

import Menu2Icon from "../library_tabler_3_2_icons/icons/PlasmicIcon__Menu2"; // plasmic-import: d1b8xWlyUKWm/icon
import CircleXIcon from "../library_tabler_3_2_icons/icons/PlasmicIcon__CircleX"; // plasmic-import: CNRVZ5IIE5Ex/icon

createPlasmicElementProxy;

export type PlasmicCustomHeader__VariantMembers = {};
export type PlasmicCustomHeader__VariantsArgs = {};
type VariantPropType = keyof PlasmicCustomHeader__VariantsArgs;
export const PlasmicCustomHeader__VariantProps = new Array<VariantPropType>();

export type PlasmicCustomHeader__ArgsType = {};
type ArgPropType = keyof PlasmicCustomHeader__ArgsType;
export const PlasmicCustomHeader__ArgProps = new Array<ArgPropType>();

export type PlasmicCustomHeader__OverridesType = {
  root?: Flex__<typeof NavigationBar>;
  img?: Flex__<typeof PlasmicImg__>;
  name?: Flex__<"h1">;
};

export interface DefaultCustomHeaderProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicCustomHeader__RenderFunc(props: {
  variants: PlasmicCustomHeader__VariantsArgs;
  args: PlasmicCustomHeader__ArgsType;
  overrides: PlasmicCustomHeader__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <NavigationBar
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      brand={
        <PlasmicLink__
          className={classNames(
            projectcss.all,
            projectcss.a,
            projectcss.a__77YCn,
            sty.link__akXc
          )}
          component={Link}
          href={`/`}
          legacyBehavior={false}
          platform={"nextjs"}
        >
          <PlasmicImg__
            data-plasmic-name={"img"}
            data-plasmic-override={overrides.img}
            alt={""}
            className={classNames(sty.img)}
            displayHeight={"100%"}
            displayMaxHeight={"none"}
            displayMaxWidth={"none"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"auto"}
            src={{
              src: "/plasmic/fiat_novum/images/youtubeChannelLogoV3Png.png",
              fullWidth: 1080,
              fullHeight: 1080,
              aspectRatio: undefined
            }}
          />

          <h1
            data-plasmic-name={"name"}
            data-plasmic-override={overrides.name}
            className={classNames(
              projectcss.all,
              projectcss.h1,
              projectcss.h1__77YCn,
              projectcss.__wab_text,
              sty.name
            )}
          >
            {"FIAT NOVUM\nENGINEERING"}
          </h1>
        </PlasmicLink__>
      }
      className={classNames(
        "__wab_instance",
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
      closeButton={
        <CircleXIcon
          className={classNames(projectcss.all, sty.svg__bvt4H)}
          role={"img"}
        />
      }
      itemsGap={8}
      menuItems={
        <React.Fragment>
          <PlasmicLink__
            className={classNames(
              projectcss.all,
              projectcss.a,
              projectcss.a__77YCn,
              projectcss.__wab_text,
              sty.link___2WA8K
            )}
            component={Link}
            href={"/blog"}
            legacyBehavior={false}
            platform={"nextjs"}
          >
            {"Blog"}
          </PlasmicLink__>
          <PlasmicLink__
            className={classNames(
              projectcss.all,
              projectcss.a,
              projectcss.a__77YCn,
              projectcss.__wab_text,
              sty.link__x1Fun
            )}
            component={Link}
            href={"/#projects"}
            legacyBehavior={false}
            platform={"nextjs"}
          >
            {"Projects"}
          </PlasmicLink__>
          <PlasmicLink__
            className={classNames(
              projectcss.all,
              projectcss.a,
              projectcss.a__77YCn,
              projectcss.__wab_text,
              sty.link__hsojC
            )}
            component={Link}
            href={"/#about"}
            legacyBehavior={false}
            platform={"nextjs"}
          >
            {"About"}
          </PlasmicLink__>
          <PlasmicLink__
            className={classNames(
              projectcss.all,
              projectcss.a,
              projectcss.a__77YCn,
              projectcss.__wab_text,
              sty.link__t05Ll
            )}
            component={Link}
            href={"/#contact"}
            legacyBehavior={false}
            platform={"nextjs"}
          >
            {"Contact"}
          </PlasmicLink__>
        </React.Fragment>
      }
      openButton={
        <Menu2Icon
          className={classNames(projectcss.all, sty.svg__yfHcd)}
          role={"img"}
        />
      }
      responsiveBreakpoint={768}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "img", "name"],
  img: ["img"],
  name: ["name"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: typeof NavigationBar;
  img: typeof PlasmicImg__;
  name: "h1";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCustomHeader__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCustomHeader__VariantsArgs;
    args?: PlasmicCustomHeader__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicCustomHeader__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicCustomHeader__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCustomHeader__ArgProps,
          internalVariantPropNames: PlasmicCustomHeader__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCustomHeader__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCustomHeader";
  } else {
    func.displayName = `PlasmicCustomHeader.${nodeName}`;
  }
  return func;
}

export const PlasmicCustomHeader = Object.assign(
  // Top-level PlasmicCustomHeader renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),
    _name: makeNodeComponent("name"),

    // Metadata about props expected for PlasmicCustomHeader
    internalVariantProps: PlasmicCustomHeader__VariantProps,
    internalArgProps: PlasmicCustomHeader__ArgProps
  }
);

export default PlasmicCustomHeader;
/* prettier-ignore-end */
